# Generated by Django 5.2.3 on 2025-07-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restourants', '0002_restaurant_address_restaurant_description_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='name_uk',
        ),
    ]
