# Generated by Django 5.2.3 on 2025-09-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address_de',
            field=models.CharField(default='Unknown address', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='address_en',
            field=models.CharField(default='Unknown address', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='address_uk',
            field=models.CharField(default='Unknown address', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_de',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_en',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_uk',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='description_de',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='description_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='description_uk',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
