# Generated by Django 5.2.3 on 2025-09-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_address_de_hotel_address_en_hotel_address_uk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description_de',
            field=models.TextField(max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description_en',
            field=models.TextField(max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description_uk',
            field=models.TextField(max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='description',
            field=models.TextField(blank=True, max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='description_de',
            field=models.TextField(blank=True, max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='description_en',
            field=models.TextField(blank=True, max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='description_uk',
            field=models.TextField(blank=True, max_length=9999, null=True),
        ),
    ]
