# Generated by Django 5.2.3 on 2025-10-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_description_alter_hotel_description_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='sity',
            field=models.CharField(default='Kyiv', max_length=200),
        ),
    ]
