# Generated by Django 5.2.3 on 2025-10-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotel_sity'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='sity_de',
            field=models.CharField(default='Kyiv', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='sity_en',
            field=models.CharField(default='Kyiv', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='sity_uk',
            field=models.CharField(default='Kyiv', max_length=200, null=True),
        ),
    ]
